
buildscript {
    repositories {
        maven {
            name = "maven-releases"
            url = uri("https://repo.julianweinelt.de/releases")
        }
        jcenter()
        maven { url = "https://files.minecraftforge.net/maven" }
        maven {
            url = "https://repo.codemc.io/repository/maven-public/"
        }

        maven {
            // location of the maven that hosts JEI files
            name = "Progwml6 maven"
            url = "https://dvs1.progwml6.com/files/maven/"
        }
        maven {
            // location of a maven mirror for JEI files, as a fallback
            name = "ModMaven"
            url = "https://modmaven.dev"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3.10'
    }
}

plugins {
    id "com.github.johnrengelman.shadow" version "1.2.3"
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = '1.2.4'
group = 'de.julianweinelt.ubm'
archivesBaseName = 'ubm'

sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    version = "1.12.2-14.23.5.2816"
    runDir = "run"

    mappings = "snapshot_20171003"
}

repositories {
    maven {
        name = "maven-releases"
        url = uri("https://repo.julianweinelt.de/releases")
    }

    maven {
        // location of the maven that hosts JEI files
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

dependencies {
    implementation("de.julianweinelt.pathfinder:PathFinderAPI:1.1.2")
    compile "org.yaml:snakeyaml:1.26"
    // compile against the JEI API but do not include it at runtime
    deobfProvided "mezz.jei:jei_1.12.2:4.16.1.1013:api"
    // at runtime, use the full JEI jar
    runtime "mezz.jei:jei_1.12.2:4.16.1.1013"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", "1.12.2"

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        expand 'version': project.version,
                'mcversion': "1.12.2"
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes(
                'FMLCorePluginContainsFMLMod': 'true',
                'Specification-Title': archivesBaseName,
                'Specification-Vendor': 'YourNameHere',
                'Specification-Version': version,
                'Implementation-Title': archivesBaseName,
                'Implementation-Version': version,
                'Implementation-Vendor': 'YourNameHere'
        )
    }
}